Repository GaikanStudio/SOGE, pull requests merged in 2024-12, with the labels that each got.

#14 Library agnostic input system and SDL based realization on top of it
  .gitmodules
  3rdparty/SDL/premake5.lua
  SOGE/include/SOGE/Containers/FriendFuncPtr.hpp
  SOGE/include/SOGE/Containers/LWString.hpp
  SOGE/include/SOGE/Core/CoreIncludeHeader.hpp
  SOGE/include/SOGE/Core/Engine.hpp
  SOGE/include/SOGE/Core/EngineTypes.hpp
  SOGE/include/SOGE/Core/EntryPoint.hpp
  SOGE/include/SOGE/Core/Event/Event.hpp
  SOGE/include/SOGE/Core/Event/EventType.hpp
  SOGE/include/SOGE/Core/EventManager.hpp
  SOGE/include/SOGE/Core/Events.hpp
  SOGE/include/SOGE/Event/CoreEvents.hpp
  SOGE/include/SOGE/Event/EventHelpers.hpp
  SOGE/include/SOGE/Event/InputEvents.hpp
  SOGE/include/SOGE/Input/Device/Gamepad.hpp
  SOGE/include/SOGE/Input/Device/InputDevice.hpp
  SOGE/include/SOGE/Input/Device/Keyboard.hpp
  SOGE/include/SOGE/Input/Device/Mouse.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLGamepad.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLInputCore.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLKeyMapManager.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLKeyboard.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLMouse.hpp
  SOGE/include/SOGE/Input/InputCore.hpp
  SOGE/include/SOGE/Input/InputIncludeHeader.hpp
  SOGE/include/SOGE/Input/InputManager.hpp
  SOGE/include/SOGE/Input/InputTypes.hpp
  SOGE/include/SOGE/Input/KeyMapManager.hpp
  SOGE/include/SOGE/SOGE.hpp
  SOGE/include/SOGE/System/Impl/SDL/SDLWindow.hpp
  SOGE/include/SOGE/System/Window.hpp
  SOGE/include/SOGE/Utils/PreprocessorHelpers.hpp
  SOGE/include/SOGE/Utils/StringHelpers.hpp
  SOGE/include/SOGE/Utils/UtilsIncludeHeader.hpp
  SOGE/include/sogepch.hpp
  SOGE/source/SOGE/Containers/LWString.cpp
  SOGE/source/SOGE/Core/Engine.cpp
  SOGE/source/SOGE/Event/InputEvents.cpp
  SOGE/source/SOGE/Input/Device/Gamepad.cpp
  SOGE/source/SOGE/Input/Device/InputDevice.cpp
  SOGE/source/SOGE/Input/Device/Keyboard.cpp
  SOGE/source/SOGE/Input/Device/Mouse.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLGamepad.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLInputCore.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLKeyMapManager.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLKeyboard.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLMouse.cpp
  SOGE/source/SOGE/Input/InputManager.cpp
  SOGE/source/SOGE/Input/InputTypes.cpp
  SOGE/source/SOGE/Input/KeyMapManager.cpp
  SOGE/source/SOGE/System/Impl/SDL/SDLWindow.cpp
  SOGE/source/SOGE/System/Window.cpp
  SOGE/source/SOGE/Utils/StringHelpers.cpp
  dependencies.lua
  premake5.lua
Labels: enhancement

#11 Module system
  SOGE/include/SOGE/Core/DI/Container.hpp
  SOGE/include/SOGE/Core/DI/Dependency.hpp
  SOGE/include/SOGE/Core/DI/Provider.hpp
  SOGE/include/SOGE/Core/Engine.hpp
  SOGE/include/SOGE/Core/Event/Event.hpp
  SOGE/include/SOGE/Core/Module.hpp
  SOGE/include/SOGE/Core/ModuleManager.hpp
  SOGE/include/SOGE/Utils/Lazy.hpp
  SOGE/source/SOGE/Core/Engine.cpp
  SOGE/source/SOGE/Core/ModuleManager.cpp
Labels: enhancement

#18 Merge render-layers branch with dev and fix of memory leak
  GAME/include/GAME/AppEntryPoint.hpp
  GAME/include/GAME/Layers/MainGameLayer.hpp
  GAME/source/GAME/AppEntryPoint.cpp
  GAME/source/GAME/Layers/MainGameLayer.cpp
  SOGE/include/SOGE/Core/Engine.hpp
  SOGE/include/SOGE/Core/Layer.hpp
  SOGE/include/SOGE/Core/LayerStack.hpp
  SOGE/include/SOGE/Input/Device/Keyboard.hpp
  SOGE/include/SOGE/Input/Device/Mouse.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLInputCore.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLKeyboard.hpp
  SOGE/include/SOGE/Input/Impl/SDL/SDLMouse.hpp
  SOGE/include/SOGE/Input/InputCore.hpp
  SOGE/include/SOGE/Input/InputModule.hpp
  SOGE/source/SOGE/Core/Engine.cpp
  SOGE/source/SOGE/Core/Layer.cpp
  SOGE/source/SOGE/Core/LayerStack.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLInputCore.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLKeyboard.cpp
  SOGE/source/SOGE/Input/Impl/SDL/SDLMouse.cpp
  SOGE/source/SOGE/Input/InputModule.cpp
Labels: bug, enhancement

#22 Compiledtime include update
  SOGE/include/SOGE/Input/InputCompilePreproc.hpp
  SOGE/include/SOGE/Utils/PreprocessorHelpers.hpp
  SOGE/source/SOGE/Input/InputModule.cpp
  SOGE/source/SOGE/Input/InputTypes.cpp
Labels: enhancement

#25 Engine lifetime
  GAME/include/GAME/AppEntryPoint.hpp
  GAME/include/GAME/Layers/MainGameLayer.hpp
  GAME/source/GAME/AppEntryPoint.cpp
  GAME/source/GAME/Layers/MainGameLayer.cpp
  SOGE/include/SOGE/Core/Engine.hpp
  SOGE/source/SOGE/Core/Engine.cpp
Labels: bug

#27 Guard against usage of engine's `GetInstance()` method in constructor
  GAME/include/GAME/AppEntryPoint.hpp
  GAME/source/GAME/AppEntryPoint.cpp
  GAME/source/GAME/Layers/MainGameLayer.cpp
  SOGE/include/SOGE/Core/Engine.hpp
  SOGE/source/SOGE/Core/Engine.cpp
Labels: bug, refactoring
